### ISSUE TITLE
Jump to new versions in Ubuntu

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#542]
# Package status for Ubuntu Xenial (16.04)

**Task list:**
- [x] gazebo7
- [x] ice-36
- [x] VTK 7 (The Visualization Toolkit)
- [x] PCL 1.8 (Point Cloud Library)
    - [x] Openni2 (In Xenial it is in libopenni2-dev package)
- [x] Python 3.5
- [x] Qt 5
- [x] Opencv 3.1

## Gazebo7 
It must be to make small modifications to the plug-ins work with gazebo7, some changes of function names (GetName() to Name(),...), elements that boost, that are now in the library C++ standard and little else.

In his time did a [first version of the plugins](https://github.com/aitormf/JdeRobot/tree/gazebo7.2), but we will have to review them with the updates we have been doing.

Tested in Xenial and works well, For install it, we have used [oficial installation](http://gazebosim.org/tutorials?tut=install_ubuntu) of gazebo:

## Ice-3.6
We can make the jump without changing any code, the problem is when it comes to Ice 3.6 installation, to install the part of C++ and Java is enough to do the following:

<pre>sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997

sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu$(lsb_release -rs) stable main"

sudo apt-get update

sudo apt-get install libbz2-dev zeroc-ice-all-runtime zeroc-ice-all-dev</pre>

But to install Ice for python we need use Pip:

<pre>pip install zeroc-ice</pre>

## Opencv3
The only thing that I can bring on this part is that I've been using it with TeachingRobotics in python on windows and I have not had to touch anything to make it work.

We need create a package:

- [x] Solved dependencies
- [x] Built
- [x] Tested
With the package created, all work well without changes

## VTK 7 (The Visualization Toolkit)
We have tested with several 6.x but these depend on python 2.7 and 5 QT together are incompatible because pyQt5 (Allows you to use QT with python) only  works in python 3.5. That is why we are going to compile from source VTK7 which is the first with stable support for Python 3.x and QT5

- [x] Solved dependencies
- [x] Built
- [x] Tested

## PCL 1.8 (Point Cloud Library)
It depends on VTK and as yet none compiled with VTK7 we have to do it ourselves.

- [x] Solved dependencies
- [x] Built
- [x] Tested

With the package created, all work well without changes
## Qt 5
We need jump to Qt5 because VTK 6.x and 7 depend on QT5 and because [Qt Company no longer supports Qt v4](https://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/).

This adds other problem because we use QWT lib for some widgets like fligth indicators and there is no version for pyQT5 because that will have to change these widgets to eliminate this dependence.

We have found a [library](https://sourceforge.net/projects/qfi/) that contains  fligth indicators without qwt. Now we need create a package with it and port it to python
### qfi
- [x] Solved dependencies
- [x] Built
- [x] Tested
- [x] ported to python

## Python 3.5

[pyQt5](https://pypi.python.org/pypi/PyQt5) only works with python 3.5 by which to avoid conflicts, should jump to this version

**Comment by aitormf** [comment]
With the backports of VTK and PCL made by @lr-morales already not have problems by that side, but now I have seen another new, in Xenial is uses cmake 3.5 and there are changes from the 2.8.

CMake shows me the following (see above all the final warnings):
<pre>
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
version:5.3.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gsl'
--   Found gsl, version 2.1
-- Checking for module 'eigen3'
--   Found eigen3, version 3.2.92
/root/JdeRobot/src/libs/colorspaces
/root/JdeRobot/src/libs/jderobotutil
/root/JdeRobot/src/libs/progeo
/root/JdeRobot/src/libs/pioneer
/root/JdeRobot/src/libs/fuzzylib
/root/JdeRobot/src/libs/visionlib
/root/JdeRobot/src/libs/parallelIce
*** ALUT not found
-- Checking for one of the modules 'OPTIONAL;ardronelib'
-- ardronelib NOT FOUND.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   chrono
--   date_time
--   atomic
   -- CUDA not found!!
*** CWIID LIBRARIES FOUND
-- Ice
-- Found PY_Ice: /usr/lib/python2.7/dist-packages/Ice.pyc  
-- matplotlib
-- Found PY_matplotlib: /usr/lib/python2.7/dist-packages/matplotlib  
-- numpy
-- Found PY_numpy: /usr/lib/python2.7/dist-packages/numpy  
-- cv2
-- Found PY_cv2: /usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so  
-- PyQt4
-- Found PY_PyQt4: /usr/lib/python2.7/dist-packages/PyQt4  
-- PyQt4.Qwt5
-- Found PY_PyQt4.Qwt5: /usr/lib/python2.7/dist-packages/PyQt4/Qwt5  
*** Fireware ok
*** GAZEBO LIBRARIES FOUND: /usr/include/gazebo-7;/usr/include/sdformat-4.1;/usr/include/ignition/math2 - 
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.30
-- Checking for module 'gtkgl-2.0'
--   Found gtkgl-2.0, version 2.0.1
-- Checking for module 'gtkmm-2.4'
--   Found gtkmm-2.4, version 2.24.4
-- Checking for module 'libglademm-2.4'
--   Found libglademm-2.4, version 2.6.7
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.48.0
-- Checking for module 'libgnomecanvas-2.0'
--   Found libgnomecanvas-2.0, version 2.30.3
-- Checking for module 'libgnomecanvasmm-2.6'
--   Found libgnomecanvasmm-2.6, version 2.26.0
-- Checking for module 'gtkglextmm-1.2'
--   Found gtkglextmm-1.2, version 1.2.0
*** Goocanvasmm LIBRARIES FOUND
*** ICE ok
 kobuki_LIBRARIES 
*** kobuki not found
LIBFREENECT NOT FOUND
*** libusb FOUND
-- Checking for module 'libxml++-2.6'
--   Found libxml++-2.6, version 2.40.1
Libxml++ libraries found at 
*** LIBXML2 ok
*** Nite not found
NITE2 library not found
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
*** OGRe LIBRARIES FOUND: /usr/include/OGRE
***OpenCV Version: 2.4.9.1
***OpenCV CORE LIBS: opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d;opencv_video;opencv_objdetect
***OpenCV GUI LIBS: opencv_highgui;opencv_calib3d
***OpenCV EXTRA LIBS: opencv_contrib;opencv_gpu;opencv_legacy
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
OpenGL libraries found at /usr/lib/x86_64-linux-gnu/libglut.so;/usr/lib/x86_64-linux-gnu/libXmu.so;/usr/lib/x86_64-linux-gnu/libXi.so
-- Looking for __i386__
-- Looking for __i386__ - not found
-- OpenNi found at /usr/lib/libOpenNI.so
-- OpenNI2 found at /usr/include/openni2
-------------CMake will install local OpenNI2 lib and Driver
-- Checking for one of the modules 'openssl'
-- Using OpenSSL 1.0.2g
-- Checking for module 'eigen3'
--   Found eigen3, version 3.2.92
-- Found eigen: /usr/include/eigen3  
-- Checking for module 'libopenni'
--   Found libopenni, version 1.5.4.0
-- Found openni: /usr/lib/libOpenNI.so  
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- Found libusb-1.0: /usr/include  
-- Checking for module 'flann'
--   Found flann, version 1.8.4
-- Found Flann: /usr/lib/x86_64-linux-gnu/libflann_cpp_s.a  
-- Found qhull: /usr/lib/x86_64-linux-gnu/libqhull.so  
-- Found PCL_COMMON: /usr/lib/x86_64-linux-gnu/libpcl_common.so  
-- Found PCL_OCTREE: /usr/lib/x86_64-linux-gnu/libpcl_octree.so  
-- Found PCL_IO: /usr/lib/x86_64-linux-gnu/libpcl_io.so  
-- Found PCL_KDTREE: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so  
-- Found PCL_SEARCH: /usr/lib/x86_64-linux-gnu/libpcl_search.so  
-- Found PCL_SAMPLE_CONSENSUS: /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so  
-- Found PCL_FILTERS: /usr/lib/x86_64-linux-gnu/libpcl_filters.so  
-- Found PCL_GEOMETRY: /usr/include/pcl-1.8  
-- Found PCL_VISUALIZATION: /usr/lib/x86_64-linux-gnu/libpcl_visualization.so  
-- Found PCL_OUTOFCORE: /usr/lib/x86_64-linux-gnu/libpcl_outofcore.so  
-- Found PCL_2D: /usr/include/pcl-1.8  
-- Found PCL_FEATURES: /usr/lib/x86_64-linux-gnu/libpcl_features.so  
-- Found PCL_ML: /usr/lib/x86_64-linux-gnu/libpcl_ml.so  
-- Found PCL_SEGMENTATION: /usr/lib/x86_64-linux-gnu/libpcl_segmentation.so  
-- Found PCL_KEYPOINTS: /usr/lib/x86_64-linux-gnu/libpcl_keypoints.so  
-- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so  
-- Found PCL_REGISTRATION: /usr/lib/x86_64-linux-gnu/libpcl_registration.so  
-- Found PCL_RECOGNITION: /usr/lib/x86_64-linux-gnu/libpcl_recognition.so  
-- Found PCL_PEOPLE: /usr/lib/x86_64-linux-gnu/libpcl_people.so  
-- Found PCL_STEREO: /usr/lib/x86_64-linux-gnu/libpcl_stereo.so  
-- Found PCL_TRACKING: /usr/lib/x86_64-linux-gnu/libpcl_tracking.so  
-- Found PCL_APPS: /usr/lib/x86_64-linux-gnu/libpcl_apps.so  
-- Found PCL_IN_HAND_SCANNER: /usr/include/pcl-1.8  
-- Found PCL_MODELER: /usr/include/pcl-1.8  
-- Found PCL_POINT_CLOUD_EDITOR: /usr/include/pcl-1.8  
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.11", minimum required is "2") 
/usr/lib/python2.7
*** QT LIBRARIES Found LIBRARIES FOUND
-- *** Qwt version 5 required
-- *** QWT_LIBRARY found
*** LIBTINYXML ok
*** Xerces ok
/usr/include/libxml2
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Building ICE Interfaces for:
-- 	CPP
-- 	Java
-- 	Python
-- Processing library easyiceconfig_cpp
-- Processing library parallelIce_py
-- Processing library fuzzylib
-- Processing library progeo
-- Processing library easyiceconfig_py
-- Processing library depthLib
-- Processing library geometry
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Processing library ns
-- Processing library pioneer
-- Processing library jderobotViewer
-- Processing library xmlParser
-- Processing library jderobotHandlers
-- Processing library log
version:5.3.1
-- Processing library resourcelocator
-- Processing library visionlib
-- Processing library jderobotutil
-- Processing library parallelIce
-- Processing tool 3DViewer
-- Processing tool basic_component
-- Processing tool rgbdViewer
-- Processing tool cameraCalibrator
-- Processing tool cameraview
-- Processing tool opencvdemo
-- Processing tool namingService
-- Processing tool naoviewer
-- Processing tool navigatorCamera
-- Processing tool rgbdCalibrator
-- Processing tool rgbdManualCalibrator
-- Processing tool kobukiViewer
-- Processing tool replayer2
-- Processing tool visualHFSM
-- Processing tool replayController
-- Processing tool giraffeClient
-- Processing tool uav_viewer
-- Processing tool colorTuner
-- Processing tool recorder2
-- Processing driver emSensorDriver
WiringPi library is required to build emSensorDriver, skipping driver bulid.
-- Processing driver kobuki_driver
-- Processing driver kinect2server
Disabled
-- Processing driver cameraserver
-- Processing driver laser_server
-- Processing driver naoserver
-- Processing driver ardrone_server
CMake Warning at src/drivers/ardrone_server/CMakeLists.txt:92 (message):
  ardrone_server marked to build, but required dependencies were not met.

  		You should install third party library: ardonelib


-- Processing driver giraffeServer
-- Processing driver openniServer
-- Processing driver basic_server
-- Processing driver gazeboserver
-- Processing plugin turtlebot
-- Processing plugin flyingKinect2
-- Processing plugin pioneer
-- Processing plugin kinect
-- Processing plugin f1
-- Processing plugin car
-- Processing plugin quadrotor2
-- Processing driver openni1Server
-- Processing driver pclRGBDServer
dpkg-deb: building package 'jderobot-deps-dev' in '.dpkg_pkgs/jderobot-deps-dev_5.4.0_all.deb'.
dpkg-deb: building package 'jderobot-deps' in '.dpkg_pkgs/jderobot-deps_5.4.0_all.deb'.
-- Configuring done
CMake Warning (dev) at src/libs/jderobotViewer/CMakeLists.txt:13 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "jderobotViewerShare" links to target "Qt5::Widgets" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/tools/3DViewer/CMakeLists.txt:18 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "3DViewer" links to target "Qt5::Widgets" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/drivers/gazeboserver/plugins/turtlebot/CMakeLists.txt:49 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "kinectPluginTurtlebotJde" links to target "Qt5::Widgets" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/drivers/gazeboserver/plugins/flyingKinect2/CMakeLists.txt:49 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "gazebo_kinectplugin" links to target "Qt5::Widgets" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/drivers/gazeboserver/plugins/kinect/CMakeLists.txt:18 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "kinectPlugin" links to target "Qt5::Widgets" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/drivers/pclRGBDServer/CMakeLists.txt:20 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "pclRGBDServer" links to target "Qt5::Widgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /root/JdeRobot/build
</pre>

**Comment by fqez** [comment]
I will see you tomorrow, so we can check this issue together! It seems to be failing only with the linking of Qt5::Widgets. If those components work well, we can supress the warnings with ```cmake_policy``` command it seems.

**Comment by aitormf** [comment]
Gazebo7 and Ice 3.6 are already tested in 16.04 and run well. But now other dependencies of the project we require to update others that have by have incompatibilities between them.

- VTK5-> VTK7
- PCL-> PCL1.8
- Python2.7-> Python3.5
- Qt4.8-> Qt5.7

Add the new information to the first post

**Comment by aitormf** [comment]
PCL1.8, VTK7 and Opencv 3.1 are already tested in 16.04 and run well. 

We have found library to replace qwt, I have added more information in first post

**Comment by aitormf** [comment]
I have ported QFlightInstruments (qfi) Altimeter from C++ to python: 
[![QFlightInstruments Altimeter Python](http://img.youtube.com/vi/cP-5B_G72CA/0.jpg)](http://www.youtube.com/watch?v=cP-5B_G72CA)

**Comment by fqez** [comment]
Jump done for Ubuntu Xenial 16.04
